
version: "3.9"
services:

  to-do-list-app:
    build:
      context: .
    restart: always
    ports:
      - "8400:8400"
    networks:
      employee-mysql:
    depends_on:
      - todolist-mysql

  todolist-mysql:
    image: mysql:8
    networks:
      employee-mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo_list
    ports:
    - "3306:3306"

networks:
  employee-mysql: