spring:
  application:
    name: todo-list
  springdoc:
    api-docs:
      path: /todo-list/docs
    swagger-ui:
      path: /todo-list/api-docs/
  datasource:
    url: jdbc:mysql://todolist-mysql/todo_list
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
server:
  port: 8400