spring:
  application:
    name: todo-list
  springdoc:
    api-docs:
      path: /todo-list/docs
    swagger-ui:
      path: /todo-list/api-docs/
  server:
    port : 8400
  datasource:
    url: jdbc:mysql://localhost/todo_list?useSSL=false
    username: root
    password:
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true